import { PrismaClient, Role, Gender, Concentration } from '@prisma/client'
import bcrypt from 'bcrypt'
import crypto from 'crypto'

const prisma = new PrismaClient()

// Inline generateSlug to make seed self-contained for production builds
function generateSlug(brand: string, name: string, concentration: string): string {
  const concentrationShort = concentration
    .replace(/_/g, ' ')
    .replace('Extrait de Parfum', 'Extrait')

  const combined = `${brand} ${name} ${concentrationShort}`

  return combined
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/&/g, 'and')
    .replace(/['"']/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .replace(/-+/g, '-')
}

function generateSecurePassword(): string {
  return crypto.randomBytes(16).toString('base64url')
}

// Map JSON concentration to Prisma enum
function mapConcentration(concentration: string): Concentration {
  const mapping: Record<string, Concentration> = {
    'Eau de Parfum': Concentration.Eau_de_Parfum,
    'Eau de Toilette': Concentration.Eau_de_Toilette,
    'Eau de Toilette Intense': Concentration.Eau_de_Toilette,
    'Cologne': Concentration.Eau_de_Cologne,
    'Eau de Cologne': Concentration.Eau_de_Cologne,
    'Parfum': Concentration.Parfum,
    'Extrait de Parfum': Concentration.Extrait_de_Parfum,
  }
  return mapping[concentration] || Concentration.Eau_de_Parfum
}

// Map JSON gender to Prisma enum
function mapGender(gender: string): Gender {
  const mapping: Record<string, Gender> = {
    'Men': Gender.Men,
    'Women': Gender.Women,
    'Unisex': Gender.Unisex,
  }
  return mapping[gender] || Gender.Unisex
}

// Perfume data
const perfumes = [
  {
    id: 1,
    name: "No. 5",
    brand: "Chanel",
    concentration: "Eau de Parfum",
    gender: "Women",
    fragranceFamily: "Floral Aldehyde",
    topNotes: ["Aldehydes", "Ylang-Ylang", "Neroli", "Bergamot"],
    heartNotes: ["Jasmine", "Rose", "Lily of the Valley", "Iris"],
    baseNotes: ["Sandalwood", "Vetiver", "Vanilla", "Amber", "Musk"],
    volumeMl: 100,
    priceUSD: 150,
    launchYear: 1921,
    perfumer: "Ernest Beaux",
    longevity: "Long-lasting",
    sillage: "Strong",
    season: ["Spring", "Fall"],
    occasion: ["Evening", "Special"],
    rating: 4.5,
    description: "The iconic fragrance that defined modern perfumery. A timeless bouquet of florals wrapped in powdery aldehydes."
  },
  {
    id: 2,
    name: "Sauvage",
    brand: "Dior",
    concentration: "Eau de Toilette",
    gender: "Men",
    fragranceFamily: "Aromatic Fougere",
    topNotes: ["Calabrian Bergamot", "Pepper"],
    heartNotes: ["Sichuan Pepper", "Lavender", "Pink Pepper", "Vetiver", "Patchouli", "Geranium", "Elemi"],
    baseNotes: ["Ambroxan", "Cedar", "Labdanum"],
    volumeMl: 100,
    priceUSD: 130,
    launchYear: 2015,
    perfumer: "François Demachy",
    longevity: "Long-lasting",
    sillage: "Strong",
    season: ["All"],
    occasion: ["Daily", "Office", "Evening"],
    rating: 4.3,
    description: "Raw and noble, a powerful juice inspired by wide-open spaces under a blue sky. Fresh and intensely woody."
  },
  {
    id: 3,
    name: "Black Orchid",
    brand: "Tom Ford",
    concentration: "Eau de Parfum",
    gender: "Unisex",
    fragranceFamily: "Oriental Floral",
    topNotes: ["Truffle", "Gardenia", "Black Currant", "Ylang-Ylang", "Jasmine", "Bergamot"],
    heartNotes: ["Orchid", "Spices", "Gardenia", "Fruity Notes", "Lotus Wood"],
    baseNotes: ["Patchouli", "Sandalwood", "Dark Chocolate", "Incense", "Amber", "Vanilla", "Vetiver", "Balsam"],
    volumeMl: 100,
    priceUSD: 180,
    launchYear: 2006,
    perfumer: "David Apel",
    longevity: "Very long-lasting",
    sillage: "Strong",
    season: ["Fall", "Winter"],
    occasion: ["Evening", "Special"],
    rating: 4.4,
    description: "A luxurious and sensual fragrance of rich, dark accords and an alluring potion of black orchids and spice."
  },
  {
    id: 4,
    name: "La Vie Est Belle",
    brand: "Lancôme",
    concentration: "Eau de Parfum",
    gender: "Women",
    fragranceFamily: "Gourmand",
    topNotes: ["Black Currant", "Pear"],
    heartNotes: ["Iris", "Jasmine", "Orange Blossom"],
    baseNotes: ["Praline", "Vanilla", "Patchouli", "Tonka Bean"],
    volumeMl: 75,
    priceUSD: 135,
    launchYear: 2012,
    perfumer: "Olivier Polge",
    longevity: "Long-lasting",
    sillage: "Moderate",
    season: ["Fall", "Winter"],
    occasion: ["Daily", "Evening"],
    rating: 4.2,
    description: "A declaration of joy and happiness. The first ever iris gourmand, combining the elegance of iris with the sweetness of praline."
  },
  {
    id: 5,
    name: "Bleu de Chanel",
    brand: "Chanel",
    concentration: "Eau de Parfum",
    gender: "Men",
    fragranceFamily: "Woody Aromatic",
    topNotes: ["Grapefruit", "Lemon", "Mint", "Pink Pepper"],
    heartNotes: ["Ginger", "Nutmeg", "Jasmine", "Iso E Super"],
    baseNotes: ["Incense", "Vetiver", "Cedar", "Sandalwood", "Patchouli", "Labdanum", "Olibanum"],
    volumeMl: 100,
    priceUSD: 165,
    launchYear: 2014,
    perfumer: "Jacques Polge",
    longevity: "Long-lasting",
    sillage: "Moderate",
    season: ["All"],
    occasion: ["Office", "Daily", "Evening"],
    rating: 4.5,
    description: "A woody aromatic fragrance for the man who defies convention. Fresh and profoundly sensual."
  },
  {
    id: 6,
    name: "Light Blue",
    brand: "Dolce & Gabbana",
    concentration: "Eau de Toilette",
    gender: "Women",
    fragranceFamily: "Citrus Floral",
    topNotes: ["Sicilian Lemon", "Apple", "Cedar", "Bellflower"],
    heartNotes: ["Bamboo", "Jasmine", "White Rose"],
    baseNotes: ["Cedar", "Amber", "Musk"],
    volumeMl: 100,
    priceUSD: 108,
    launchYear: 2001,
    perfumer: "Olivier Cresp",
    longevity: "Moderate",
    sillage: "Moderate",
    season: ["Spring", "Summer"],
    occasion: ["Daily", "Casual"],
    rating: 4.1,
    description: "The scent of Mediterranean summer. Refreshing and sparkling, evoking the sensuality of the sea."
  },
  {
    id: 7,
    name: "Aventus",
    brand: "Creed",
    concentration: "Eau de Parfum",
    gender: "Men",
    fragranceFamily: "Fruity Chypre",
    topNotes: ["Pineapple", "Bergamot", "Black Currant", "Apple"],
    heartNotes: ["Birch", "Patchouli", "Moroccan Jasmine", "Rose"],
    baseNotes: ["Musk", "Oak Moss", "Ambergris", "Vanilla"],
    volumeMl: 100,
    priceUSD: 445,
    launchYear: 2010,
    perfumer: "Olivier Creed",
    longevity: "Very long-lasting",
    sillage: "Strong",
    season: ["All"],
    occasion: ["Office", "Evening", "Special"],
    rating: 4.6,
    description: "A sophisticated fruity chypre celebrating strength, power, and success. Inspired by the dramatic life of Emperor Napoleon."
  },
  {
    id: 8,
    name: "Coco Mademoiselle",
    brand: "Chanel",
    concentration: "Eau de Parfum",
    gender: "Women",
    fragranceFamily: "Oriental Floral",
    topNotes: ["Orange", "Bergamot", "Grapefruit"],
    heartNotes: ["Rose", "Jasmine", "Lychee"],
    baseNotes: ["Musk", "Patchouli", "Opoponax", "Vanilla", "Vetiver", "White Musk"],
    volumeMl: 100,
    priceUSD: 162,
    launchYear: 2001,
    perfumer: "Jacques Polge",
    longevity: "Long-lasting",
    sillage: "Moderate",
    season: ["Spring", "Fall"],
    occasion: ["Daily", "Office", "Evening"],
    rating: 4.4,
    description: "A fresh oriental fragrance for the irresistible woman. Sparkling, bold, and perfectly balanced."
  },
  {
    id: 9,
    name: "Acqua di Gio",
    brand: "Giorgio Armani",
    concentration: "Eau de Toilette",
    gender: "Men",
    fragranceFamily: "Aquatic Aromatic",
    topNotes: ["Calabrian Bergamot", "Neroli", "Green Tangerine"],
    heartNotes: ["Sea Water Notes", "Jasmine", "Calone", "Rosemary"],
    baseNotes: ["White Musk", "Cedar", "Oakmoss", "Amber", "Patchouli"],
    volumeMl: 100,
    priceUSD: 110,
    launchYear: 1996,
    perfumer: "Alberto Morillas",
    longevity: "Moderate",
    sillage: "Moderate",
    season: ["Spring", "Summer"],
    occasion: ["Daily", "Casual", "Office"],
    rating: 4.2,
    description: "The essence of freedom, full of wind, water, and sun. A timeless aquatic fragrance inspired by Pantelleria Island."
  },
  {
    id: 10,
    name: "Miss Dior",
    brand: "Dior",
    concentration: "Eau de Parfum",
    gender: "Women",
    fragranceFamily: "Floral Chypre",
    topNotes: ["Blood Orange", "Mandarin Orange"],
    heartNotes: ["Rose", "Peony", "Lily of the Valley", "Jasmine"],
    baseNotes: ["Patchouli", "Musk", "Rosewood"],
    volumeMl: 100,
    priceUSD: 155,
    launchYear: 2012,
    perfumer: "François Demachy",
    longevity: "Long-lasting",
    sillage: "Moderate",
    season: ["Spring", "Summer"],
    occasion: ["Daily", "Special"],
    rating: 4.3,
    description: "Fresh and sparkling, wrapped in a wave of grasse rose and peony. A love declaration that celebrates life."
  },
  {
    id: 11,
    name: "1 Million",
    brand: "Paco Rabanne",
    concentration: "Eau de Toilette",
    gender: "Men",
    fragranceFamily: "Spicy Leather",
    topNotes: ["Grapefruit", "Blood Mandarin", "Peppermint"],
    heartNotes: ["Rose", "Cinnamon", "Spices"],
    baseNotes: ["Leather", "Amber", "Woody Notes", "Patchouli"],
    volumeMl: 100,
    priceUSD: 95,
    launchYear: 2008,
    perfumer: "Christophe Raynaud",
    longevity: "Long-lasting",
    sillage: "Strong",
    season: ["Fall", "Winter"],
    occasion: ["Evening", "Special"],
    rating: 4.0,
    description: "A provocative blend of fresh mint, blood mandarin, rose absolute and golden leather. Pure audacity."
  },
  {
    id: 12,
    name: "J'adore",
    brand: "Dior",
    concentration: "Eau de Parfum",
    gender: "Women",
    fragranceFamily: "Floral Fruity",
    topNotes: ["Pear", "Melon", "Magnolia", "Peach", "Bergamot", "Mandarin Orange"],
    heartNotes: ["Jasmine", "Lily of the Valley", "Tuberose", "Rose", "Plum", "Violet", "Orchid", "Freesia"],
    baseNotes: ["Musk", "Vanilla", "Cedar", "Blackberry", "Sandalwood"],
    volumeMl: 100,
    priceUSD: 155,
    launchYear: 1999,
    perfumer: "Calice Becker",
    longevity: "Long-lasting",
    sillage: "Moderate",
    season: ["Spring", "Summer"],
    occasion: ["Daily", "Evening", "Special"],
    rating: 4.3,
    description: "A modern, glamorous fragrance, simultaneously fruity and floral. Absolute femininity in a golden cascade."
  },
  {
    id: 13,
    name: "Oud Wood",
    brand: "Tom Ford",
    concentration: "Eau de Parfum",
    gender: "Unisex",
    fragranceFamily: "Woody Oriental",
    topNotes: ["Rosewood", "Chinese Pepper", "Cardamom"],
    heartNotes: ["Oud Wood", "Sandalwood", "Vetiver"],
    baseNotes: ["Tonka Bean", "Amber"],
    volumeMl: 100,
    priceUSD: 290,
    launchYear: 2007,
    perfumer: "Richard Herpin",
    longevity: "Very long-lasting",
    sillage: "Moderate",
    season: ["Fall", "Winter"],
    occasion: ["Evening", "Special"],
    rating: 4.4,
    description: "Rare. Exotic. Distinctive. A precious oud aged over centuries, blended with smoky woods and exotic spice."
  },
  {
    id: 14,
    name: "Good Girl",
    brand: "Carolina Herrera",
    concentration: "Eau de Parfum",
    gender: "Women",
    fragranceFamily: "Oriental Floral",
    topNotes: ["Almond", "Coffee"],
    heartNotes: ["Tuberose", "Jasmine Sambac", "Orange Blossom"],
    baseNotes: ["Tonka Bean", "Cacao", "Sandalwood", "Cinnamon", "Cashmere Wood", "Amber", "Benzoin", "Musk", "Cedar", "Praline", "Vanilla", "Patchouli"],
    volumeMl: 80,
    priceUSD: 128,
    launchYear: 2016,
    perfumer: "Louise Turner",
    longevity: "Very long-lasting",
    sillage: "Strong",
    season: ["Fall", "Winter"],
    occasion: ["Evening", "Special"],
    rating: 4.2,
    description: "A bold fragrance of duality and contrast. Floral meets woody, light meets dark in this statement scent."
  },
  {
    id: 15,
    name: "Terre d'Hermès",
    brand: "Hermès",
    concentration: "Eau de Toilette",
    gender: "Men",
    fragranceFamily: "Woody Spicy",
    topNotes: ["Orange", "Grapefruit"],
    heartNotes: ["Pepper", "Pelargonium", "Atlas Cedar", "Vetiver"],
    baseNotes: ["Benzoin", "Patchouli"],
    volumeMl: 100,
    priceUSD: 135,
    launchYear: 2006,
    perfumer: "Jean-Claude Ellena",
    longevity: "Long-lasting",
    sillage: "Moderate",
    season: ["Spring", "Fall"],
    occasion: ["Office", "Daily"],
    rating: 4.4,
    description: "A woody and mineral fragrance. A metaphor for raw materials, depicting the alchemist's relationship with the Earth."
  },
  {
    id: 16,
    name: "Flowerbomb",
    brand: "Viktor & Rolf",
    concentration: "Eau de Parfum",
    gender: "Women",
    fragranceFamily: "Floral Oriental",
    topNotes: ["Tea", "Bergamot", "Osmanthus"],
    heartNotes: ["Orchid", "Jasmine", "Rose", "Freesia", "African Orange Flower"],
    baseNotes: ["Musk", "Patchouli", "Vanilla"],
    volumeMl: 100,
    priceUSD: 185,
    launchYear: 2005,
    perfumer: "Olivier Polge",
    longevity: "Long-lasting",
    sillage: "Strong",
    season: ["Fall", "Winter"],
    occasion: ["Evening", "Special"],
    rating: 4.2,
    description: "An explosive floral bouquet. Full-bodied and opulent, like a thousand flowers exploding with pleasure."
  },
  {
    id: 17,
    name: "Le Male",
    brand: "Jean Paul Gaultier",
    concentration: "Eau de Toilette",
    gender: "Men",
    fragranceFamily: "Oriental Fougere",
    topNotes: ["Mint", "Lavender", "Bergamot", "Cardamom", "Artemisia"],
    heartNotes: ["Orange Blossom", "Cumin", "Cinnamon"],
    baseNotes: ["Vanilla", "Tonka Bean", "Sandalwood", "Amber", "Cedar"],
    volumeMl: 125,
    priceUSD: 98,
    launchYear: 1995,
    perfumer: "Francis Kurkdjian",
    longevity: "Long-lasting",
    sillage: "Strong",
    season: ["Fall", "Winter"],
    occasion: ["Evening", "Special"],
    rating: 4.2,
    description: "A fresh oriental classic. Contradictions of strength and sweetness, sensuality and modesty."
  },
  {
    id: 18,
    name: "Baccarat Rouge 540",
    brand: "Maison Francis Kurkdjian",
    concentration: "Eau de Parfum",
    gender: "Unisex",
    fragranceFamily: "Amber Floral",
    topNotes: ["Saffron", "Jasmine"],
    heartNotes: ["Amberwood", "Ambergris"],
    baseNotes: ["Fir Resin", "Cedar"],
    volumeMl: 70,
    priceUSD: 325,
    launchYear: 2015,
    perfumer: "Francis Kurkdjian",
    longevity: "Very long-lasting",
    sillage: "Strong",
    season: ["Fall", "Winter"],
    occasion: ["Special", "Evening"],
    rating: 4.5,
    description: "A luminous alchemy of jasmine and saffron, creating a golden aura that radiates on the skin."
  },
  {
    id: 19,
    name: "Chance",
    brand: "Chanel",
    concentration: "Eau de Toilette",
    gender: "Women",
    fragranceFamily: "Floral Spicy",
    topNotes: ["Pink Pepper", "Pineapple", "Hyacinth", "Iris"],
    heartNotes: ["Jasmine", "Citrus"],
    baseNotes: ["Musk", "Patchouli", "Amber", "Vetiver", "Vanilla"],
    volumeMl: 100,
    priceUSD: 145,
    launchYear: 2002,
    perfumer: "Jacques Polge",
    longevity: "Moderate",
    sillage: "Moderate",
    season: ["Spring", "Summer"],
    occasion: ["Daily", "Casual"],
    rating: 4.2,
    description: "An unexpected floral. Rounded and radiant, a whirlwind of happiness and fantasy."
  },
  {
    id: 20,
    name: "Dior Homme Intense",
    brand: "Dior",
    concentration: "Eau de Parfum",
    gender: "Men",
    fragranceFamily: "Floral Woody",
    topNotes: ["Lavender", "Pear"],
    heartNotes: ["Iris", "Ambrette"],
    baseNotes: ["Vetiver", "Virginia Cedar", "Leather"],
    volumeMl: 100,
    priceUSD: 145,
    launchYear: 2011,
    perfumer: "François Demachy",
    longevity: "Long-lasting",
    sillage: "Moderate",
    season: ["Fall", "Winter"],
    occasion: ["Evening", "Special"],
    rating: 4.4,
    description: "A powerful and sophisticated iris fragrance. Deep, noble, and unexpectedly seductive."
  },
  {
    id: 21,
    name: "Poison",
    brand: "Dior",
    concentration: "Eau de Toilette",
    gender: "Women",
    fragranceFamily: "Amber Spicy",
    topNotes: ["Coriander", "Plum", "Anise", "Orange", "Berries"],
    heartNotes: ["Tuberose", "Orange Blossom", "Cinnamon", "Carnation", "Rose", "Jasmine"],
    baseNotes: ["Opoponax", "Sandalwood", "Cedar", "Amber", "Honey", "Musk"],
    volumeMl: 100,
    priceUSD: 130,
    launchYear: 1985,
    perfumer: "Edouard Fléchier",
    longevity: "Very long-lasting",
    sillage: "Strong",
    season: ["Fall", "Winter"],
    occasion: ["Evening", "Special"],
    rating: 4.0,
    description: "Bold and provocative. An intoxicating oriental that made fragrance history."
  },
  {
    id: 22,
    name: "Versace Eros",
    brand: "Versace",
    concentration: "Eau de Toilette",
    gender: "Men",
    fragranceFamily: "Aromatic Fougere",
    topNotes: ["Mint", "Green Apple", "Lemon"],
    heartNotes: ["Tonka Bean", "Ambroxan", "Geranium"],
    baseNotes: ["Vanilla", "Vetiver", "Oakmoss", "Cedarwood"],
    volumeMl: 100,
    priceUSD: 102,
    launchYear: 2012,
    perfumer: "Aurelien Guichard",
    longevity: "Long-lasting",
    sillage: "Strong",
    season: ["Fall", "Winter"],
    occasion: ["Evening", "Special"],
    rating: 4.1,
    description: "A fragrance of passion and desire, inspired by Greek mythology. Powerful, confident, seductive."
  },
  {
    id: 23,
    name: "Narciso Rodriguez for Her",
    brand: "Narciso Rodriguez",
    concentration: "Eau de Parfum",
    gender: "Women",
    fragranceFamily: "Musky Floral",
    topNotes: ["Rose", "Peach"],
    heartNotes: ["Musk", "Orange Blossom"],
    baseNotes: ["Amber", "Patchouli", "Sandalwood", "Musk"],
    volumeMl: 100,
    priceUSD: 134,
    launchYear: 2006,
    perfumer: "Christine Nagel",
    longevity: "Long-lasting",
    sillage: "Moderate",
    season: ["Fall", "Winter"],
    occasion: ["Evening", "Special"],
    rating: 4.2,
    description: "A sensual heart of Egyptian musk wrapped in a luminous veil of amber. Pure, mysterious femininity."
  },
  {
    id: 24,
    name: "YSL Libre",
    brand: "Yves Saint Laurent",
    concentration: "Eau de Parfum",
    gender: "Women",
    fragranceFamily: "Oriental Fougere",
    topNotes: ["Lavender", "Mandarin Orange", "Black Currant", "Bergamot", "Petitgrain"],
    heartNotes: ["Jasmine", "Lavender", "Orange Blossom"],
    baseNotes: ["Vanilla", "Musk", "Cedar", "Ambergris"],
    volumeMl: 90,
    priceUSD: 135,
    launchYear: 2019,
    perfumer: "Anne Flipo",
    longevity: "Long-lasting",
    sillage: "Strong",
    season: ["All"],
    occasion: ["Daily", "Evening"],
    rating: 4.3,
    description: "The scent of freedom. Lavender and orange blossom enhanced by sophisticated heat."
  },
  {
    id: 25,
    name: "Valentino Uomo",
    brand: "Valentino",
    concentration: "Eau de Toilette",
    gender: "Men",
    fragranceFamily: "Oriental Woody",
    topNotes: ["Bergamot", "Myrtle"],
    heartNotes: ["Coffee", "Gianduja"],
    baseNotes: ["Leather", "Cedar", "White Musk"],
    volumeMl: 100,
    priceUSD: 118,
    launchYear: 2014,
    perfumer: "Olivier Polge",
    longevity: "Long-lasting",
    sillage: "Moderate",
    season: ["Fall", "Winter"],
    occasion: ["Evening", "Office"],
    rating: 4.1,
    description: "Italian elegance in a bottle. A sophisticated blend of coffee and leather, utterly masculine."
  },
  {
    id: 26,
    name: "Mon Paris",
    brand: "Yves Saint Laurent",
    concentration: "Eau de Parfum",
    gender: "Women",
    fragranceFamily: "Floral Fruity",
    topNotes: ["Raspberry", "Strawberry", "Pear", "Bergamot", "Orange"],
    heartNotes: ["Datura", "Peony", "Jasmine", "White Flowers"],
    baseNotes: ["Patchouli", "White Musk", "Ambroxan", "Cashmeran"],
    volumeMl: 90,
    priceUSD: 130,
    launchYear: 2016,
    perfumer: "Olivier Cresp",
    longevity: "Long-lasting",
    sillage: "Strong",
    season: ["Spring", "Fall"],
    occasion: ["Evening", "Special"],
    rating: 4.1,
    description: "A tribute to Parisian romance. An intensely fruity floral, dangerously passionate."
  },
  {
    id: 27,
    name: "Fahrenheit",
    brand: "Dior",
    concentration: "Eau de Toilette",
    gender: "Men",
    fragranceFamily: "Woody Floral",
    topNotes: ["Lavender", "Mandarin Orange", "Hawthorn", "Nutmeg", "Cedar", "Chamomile", "Bergamot"],
    heartNotes: ["Carnation", "Jasmine", "Lily of the Valley", "Nutmeg", "Sandalwood", "Violet Leaf"],
    baseNotes: ["Leather", "Tonka Bean", "Amber", "Musk", "Vetiver", "Cedar", "Patchouli"],
    volumeMl: 100,
    priceUSD: 115,
    launchYear: 1988,
    perfumer: "Jean-Louis Sieuzac",
    longevity: "Long-lasting",
    sillage: "Strong",
    season: ["Fall", "Winter"],
    occasion: ["Office", "Evening"],
    rating: 4.2,
    description: "A sensory experience between fire and ice. Distinctive gasoline and violet leaf signature."
  },
  {
    id: 28,
    name: "Shalimar",
    brand: "Guerlain",
    concentration: "Eau de Parfum",
    gender: "Women",
    fragranceFamily: "Oriental Vanilla",
    topNotes: ["Bergamot", "Lemon", "Mandarin Orange"],
    heartNotes: ["Jasmine", "Rose", "May Rose", "Orris Root"],
    baseNotes: ["Sandalwood", "Vetiver", "Opoponax", "Tonka Bean", "Vanilla", "Benzoin", "Leather", "Incense", "Musk", "Civet"],
    volumeMl: 90,
    priceUSD: 148,
    launchYear: 1925,
    perfumer: "Jacques Guerlain",
    longevity: "Very long-lasting",
    sillage: "Strong",
    season: ["Fall", "Winter"],
    occasion: ["Evening", "Special"],
    rating: 4.3,
    description: "The first ever oriental fragrance. An homage to eternal love, inspired by the gardens of Shalimar."
  },
  {
    id: 29,
    name: "Dylan Blue",
    brand: "Versace",
    concentration: "Eau de Toilette",
    gender: "Men",
    fragranceFamily: "Aromatic Fougere",
    topNotes: ["Calabrian Bergamot", "Grapefruit", "Fig Leaf", "Water Notes"],
    heartNotes: ["Violet Leaf", "Black Pepper", "Papyrus Wood", "Patchouli", "Ambroxan"],
    baseNotes: ["Musk", "Incense", "Tonka Bean", "Saffron"],
    volumeMl: 100,
    priceUSD: 102,
    launchYear: 2016,
    perfumer: "Alberto Morillas",
    longevity: "Long-lasting",
    sillage: "Strong",
    season: ["All"],
    occasion: ["Daily", "Office", "Evening"],
    rating: 4.0,
    description: "Mediterranean masculinity. An aromatic fougere of citrus and woody notes with a modern edge."
  },
  {
    id: 30,
    name: "Alien",
    brand: "Mugler",
    concentration: "Eau de Parfum",
    gender: "Women",
    fragranceFamily: "Amber Woody",
    topNotes: ["Jasmine Sambac"],
    heartNotes: ["Cashmeran Wood"],
    baseNotes: ["White Amber"],
    volumeMl: 60,
    priceUSD: 108,
    launchYear: 2005,
    perfumer: "Dominique Ropion",
    longevity: "Very long-lasting",
    sillage: "Strong",
    season: ["Fall", "Winter"],
    occasion: ["Evening", "Special"],
    rating: 4.1,
    description: "A mysterious elixir from another world. Solar, radiant jasmine in an amber cocoon."
  },
  {
    id: 31,
    name: "Angel",
    brand: "Mugler",
    concentration: "Eau de Parfum",
    gender: "Women",
    fragranceFamily: "Gourmand Oriental",
    topNotes: ["Melon", "Coconut", "Mandarin Orange", "Jasmine", "Bergamot", "Cotton Candy"],
    heartNotes: ["Honey", "Apricot", "Blackberry", "Plum", "Jasmine", "Orchid", "Lily of the Valley", "Rose"],
    baseNotes: ["Patchouli", "Musk", "Vanilla", "Caramel", "Chocolate", "Tonka Bean", "Sandalwood"],
    volumeMl: 50,
    priceUSD: 105,
    launchYear: 1992,
    perfumer: "Olivier Cresp",
    longevity: "Very long-lasting",
    sillage: "Strong",
    season: ["Fall", "Winter"],
    occasion: ["Evening", "Special"],
    rating: 4.0,
    description: "The pioneer of gourmand fragrances. A revolutionary patchouli-chocolate shock that changed perfumery."
  },
  {
    id: 32,
    name: "The One",
    brand: "Dolce & Gabbana",
    concentration: "Eau de Parfum",
    gender: "Men",
    fragranceFamily: "Woody Spicy",
    topNotes: ["Grapefruit", "Coriander", "Basil"],
    heartNotes: ["Cardamom", "Ginger", "Orange Blossom"],
    baseNotes: ["Tobacco", "Amber", "Cedar", "Labdanum"],
    volumeMl: 100,
    priceUSD: 118,
    launchYear: 2008,
    perfumer: "Olivier Polge",
    longevity: "Long-lasting",
    sillage: "Moderate",
    season: ["Fall", "Winter"],
    occasion: ["Evening", "Special"],
    rating: 4.3,
    description: "The essence of the modern gentleman. Elegant tobacco and oriental spices in perfect balance."
  },
  {
    id: 33,
    name: "Black Opium",
    brand: "Yves Saint Laurent",
    concentration: "Eau de Parfum",
    gender: "Women",
    fragranceFamily: "Oriental Vanilla",
    topNotes: ["Pink Pepper", "Orange Blossom", "Pear", "Adrenaline Accord"],
    heartNotes: ["Coffee", "Jasmine", "Bitter Almond", "Licorice", "Celosia"],
    baseNotes: ["Vanilla", "Patchouli", "Cedar", "Cashmere Wood"],
    volumeMl: 90,
    priceUSD: 140,
    launchYear: 2014,
    perfumer: "Nathalie Lorson",
    longevity: "Very long-lasting",
    sillage: "Strong",
    season: ["Fall", "Winter"],
    occasion: ["Evening", "Special"],
    rating: 4.2,
    description: "Highly addictive. A dark, mysterious coffee and vanilla shot with a rock 'n' roll edge."
  },
  {
    id: 34,
    name: "Invictus",
    brand: "Paco Rabanne",
    concentration: "Eau de Toilette",
    gender: "Men",
    fragranceFamily: "Aromatic Aquatic",
    topNotes: ["Marine Notes", "Grapefruit", "Mandarin Orange"],
    heartNotes: ["Bay Leaf", "Jasmine"],
    baseNotes: ["Amber", "Guaiac Wood", "Patchouli", "Oak Moss", "Musk"],
    volumeMl: 100,
    priceUSD: 95,
    launchYear: 2013,
    perfumer: "Veronique Nyberg",
    longevity: "Long-lasting",
    sillage: "Strong",
    season: ["Spring", "Summer"],
    occasion: ["Daily", "Sport", "Casual"],
    rating: 4.0,
    description: "A champion's scent. Fresh and powerful, like a trophy for the victorious."
  },
  {
    id: 35,
    name: "Si",
    brand: "Giorgio Armani",
    concentration: "Eau de Parfum",
    gender: "Women",
    fragranceFamily: "Chypre Fruity",
    topNotes: ["Cassis", "Black Currant", "Pear", "Freesia", "Mandarin Orange", "Bergamot"],
    heartNotes: ["Rose", "May Rose", "Osmanthus", "Neroli"],
    baseNotes: ["Ambroxan", "Patchouli", "Musk", "Vanilla", "Woody Notes", "Orris Root"],
    volumeMl: 100,
    priceUSD: 145,
    launchYear: 2013,
    perfumer: "Christine Nagel",
    longevity: "Long-lasting",
    sillage: "Moderate",
    season: ["Spring", "Fall"],
    occasion: ["Daily", "Office", "Evening"],
    rating: 4.2,
    description: "Feminine and powerful. A tribute to modern elegance with blackcurrant nectar and rose."
  },
  {
    id: 36,
    name: "Portrait of a Lady",
    brand: "Frederic Malle",
    concentration: "Eau de Parfum",
    gender: "Women",
    fragranceFamily: "Amber Floral",
    topNotes: ["Cinnamon", "Pink Pepper", "Clove", "Ginger", "Raspberry", "Bergamot", "Black Currant"],
    heartNotes: ["Rose", "Iris"],
    baseNotes: ["Patchouli", "Musk", "Sandalwood", "Benzoin", "Incense", "Amber"],
    volumeMl: 100,
    priceUSD: 350,
    launchYear: 2010,
    perfumer: "Dominique Ropion",
    longevity: "Very long-lasting",
    sillage: "Strong",
    season: ["Fall", "Winter"],
    occasion: ["Evening", "Special"],
    rating: 4.6,
    description: "A masterpiece. The biggest rose money can buy, enriched with dark, sensual patchouli."
  },
  {
    id: 37,
    name: "Spicebomb",
    brand: "Viktor & Rolf",
    concentration: "Eau de Toilette",
    gender: "Men",
    fragranceFamily: "Spicy Oriental",
    topNotes: ["Bergamot", "Grapefruit", "Pink Pepper", "Elemi"],
    heartNotes: ["Cinnamon", "Saffron", "Paprika"],
    baseNotes: ["Vetiver", "Tobacco", "Leather", "Lavandin"],
    volumeMl: 90,
    priceUSD: 120,
    launchYear: 2012,
    perfumer: "Olivier Polge",
    longevity: "Long-lasting",
    sillage: "Strong",
    season: ["Fall", "Winter"],
    occasion: ["Evening", "Special"],
    rating: 4.2,
    description: "Explosive seduction. A potent cocktail of fiery spices that detonates masculine intensity."
  },
  {
    id: 38,
    name: "L'Interdit",
    brand: "Givenchy",
    concentration: "Eau de Parfum",
    gender: "Women",
    fragranceFamily: "Floral Woody",
    topNotes: ["Pear", "Orange Blossom"],
    heartNotes: ["Tuberose", "Jasmine"],
    baseNotes: ["Vetiver", "Patchouli", "Ambroxan"],
    volumeMl: 80,
    priceUSD: 130,
    launchYear: 2018,
    perfumer: "Dominique Ropion",
    longevity: "Long-lasting",
    sillage: "Moderate",
    season: ["Spring", "Fall"],
    occasion: ["Daily", "Evening"],
    rating: 4.1,
    description: "The thrill of the forbidden. A luminous white flower composition with a dark, woody edge."
  },
  {
    id: 39,
    name: "Gucci Bloom",
    brand: "Gucci",
    concentration: "Eau de Parfum",
    gender: "Women",
    fragranceFamily: "White Floral",
    topNotes: ["Natural Tuberose", "Jasmine Bud Extract"],
    heartNotes: ["Tuberose", "Jasmine"],
    baseNotes: ["Rangoon Creeper", "Sandalwood", "Orris Root"],
    volumeMl: 100,
    priceUSD: 145,
    launchYear: 2017,
    perfumer: "Alberto Morillas",
    longevity: "Long-lasting",
    sillage: "Strong",
    season: ["Spring", "Summer"],
    occasion: ["Daily", "Evening"],
    rating: 4.1,
    description: "A thriving garden of flowers. Rich white floral notes capturing the optimism of youth."
  },
  {
    id: 40,
    name: "Tobacco Vanille",
    brand: "Tom Ford",
    concentration: "Eau de Parfum",
    gender: "Unisex",
    fragranceFamily: "Oriental Spicy",
    topNotes: ["Tobacco Leaf", "Spices"],
    heartNotes: ["Tobacco Blossom", "Vanilla", "Cacao", "Tonka Bean"],
    baseNotes: ["Dried Fruits", "Woody Notes"],
    volumeMl: 100,
    priceUSD: 290,
    launchYear: 2007,
    perfumer: "Olivier Gillotin",
    longevity: "Very long-lasting",
    sillage: "Strong",
    season: ["Fall", "Winter"],
    occasion: ["Evening", "Special"],
    rating: 4.5,
    description: "Warm and opulent. Rich tobacco and sweet vanilla create a luxurious gentleman's club atmosphere."
  },
  {
    id: 41,
    name: "My Way",
    brand: "Giorgio Armani",
    concentration: "Eau de Parfum",
    gender: "Women",
    fragranceFamily: "Floral Woody",
    topNotes: ["Orange Blossom", "Bergamot"],
    heartNotes: ["Indian Tuberose", "Egyptian Jasmine"],
    baseNotes: ["White Musk", "Virginia Cedar", "Vanilla"],
    volumeMl: 90,
    priceUSD: 135,
    launchYear: 2020,
    perfumer: "Carlos Benaim",
    longevity: "Long-lasting",
    sillage: "Moderate",
    season: ["Spring", "Summer"],
    occasion: ["Daily", "Office"],
    rating: 4.0,
    description: "A journey of discovery. Sustainable florals from around the world united in harmony."
  },
  {
    id: 42,
    name: "L'Homme",
    brand: "Yves Saint Laurent",
    concentration: "Eau de Toilette",
    gender: "Men",
    fragranceFamily: "Woody Floral",
    topNotes: ["Ginger", "Bergamot", "Lemon"],
    heartNotes: ["Violet Leaf", "Basil", "Spices", "White Pepper"],
    baseNotes: ["Tonka Bean", "Cedar", "Vetiver"],
    volumeMl: 100,
    priceUSD: 115,
    launchYear: 2006,
    perfumer: "Anne Flipo",
    longevity: "Moderate",
    sillage: "Moderate",
    season: ["All"],
    occasion: ["Office", "Daily"],
    rating: 4.2,
    description: "Urban elegance. Fresh ginger and violet leaf in a sophisticated woody framework."
  },
  {
    id: 43,
    name: "Eros Pour Femme",
    brand: "Versace",
    concentration: "Eau de Parfum",
    gender: "Women",
    fragranceFamily: "Floral Woody",
    topNotes: ["Lemon", "Bergamot", "Pomegranate", "Sicilian Lemon"],
    heartNotes: ["Jasmine Sambac", "Peony", "Lemon Blossom"],
    baseNotes: ["Sandalwood", "Ambroxan", "Musk", "Woods"],
    volumeMl: 100,
    priceUSD: 118,
    launchYear: 2014,
    perfumer: "Alberto Morillas",
    longevity: "Long-lasting",
    sillage: "Strong",
    season: ["Spring", "Summer"],
    occasion: ["Daily", "Evening"],
    rating: 4.0,
    description: "Divine feminine sensuality. Fresh, seductive, and utterly captivating like the goddess of love."
  },
  {
    id: 44,
    name: "Interlude Man",
    brand: "Amouage",
    concentration: "Eau de Parfum",
    gender: "Men",
    fragranceFamily: "Oriental Woody",
    topNotes: ["Oregano", "Pimento Berry", "Bergamot"],
    heartNotes: ["Olibanum", "Opoponax", "Amber", "Labdanum"],
    baseNotes: ["Leather", "Oud", "Sandalwood", "Musk", "Cistus"],
    volumeMl: 100,
    priceUSD: 340,
    launchYear: 2012,
    perfumer: "Pierre Negrin",
    longevity: "Very long-lasting",
    sillage: "Strong",
    season: ["Fall", "Winter"],
    occasion: ["Evening", "Special"],
    rating: 4.4,
    description: "Operatic intensity. A sensory journey through incense, spice, and smoldering woods."
  },
  {
    id: 45,
    name: "Delina",
    brand: "Parfums de Marly",
    concentration: "Eau de Parfum",
    gender: "Women",
    fragranceFamily: "Floral Fruity",
    topNotes: ["Rhubarb", "Lychee", "Bergamot", "Nutmeg"],
    heartNotes: ["Turkish Rose", "Peony", "Vanilla"],
    baseNotes: ["Musk", "Cashmeran", "Cedar", "Incense"],
    volumeMl: 75,
    priceUSD: 310,
    launchYear: 2017,
    perfumer: "Quentin Bisch",
    longevity: "Very long-lasting",
    sillage: "Strong",
    season: ["Spring", "Fall"],
    occasion: ["Evening", "Special"],
    rating: 4.4,
    description: "Royal femininity. Enchanting florals with a modern, sparkling edge. Irresistibly romantic."
  },
  {
    id: 46,
    name: "Cool Water",
    brand: "Davidoff",
    concentration: "Eau de Toilette",
    gender: "Men",
    fragranceFamily: "Aromatic Aquatic",
    topNotes: ["Sea Water", "Lavender", "Mint", "Green Notes", "Coriander", "Rosemary"],
    heartNotes: ["Jasmine", "Sandalwood", "Geranium", "Neroli"],
    baseNotes: ["Musk", "Vetiver", "Cedar", "Oakmoss", "Tobacco", "Amber"],
    volumeMl: 125,
    priceUSD: 55,
    launchYear: 1988,
    perfumer: "Pierre Bourdon",
    longevity: "Moderate",
    sillage: "Moderate",
    season: ["Spring", "Summer"],
    occasion: ["Daily", "Casual", "Sport"],
    rating: 3.9,
    description: "Ocean freshness. A classic aquatic that defined the fresh masculine genre for a generation."
  },
  {
    id: 47,
    name: "Lost Cherry",
    brand: "Tom Ford",
    concentration: "Eau de Parfum",
    gender: "Unisex",
    fragranceFamily: "Gourmand Fruity",
    topNotes: ["Bitter Almond", "Black Cherry", "Cherry Liqueur"],
    heartNotes: ["Turkish Rose", "Jasmine Sambac", "Peru Balsam"],
    baseNotes: ["Sandalwood", "Vetiver", "Tonka Bean", "Cedar", "Roasted Tonka", "Vanilla"],
    volumeMl: 50,
    priceUSD: 360,
    launchYear: 2018,
    perfumer: "Unknown",
    longevity: "Very long-lasting",
    sillage: "Strong",
    season: ["Fall", "Winter"],
    occasion: ["Evening", "Special"],
    rating: 4.2,
    description: "Luscious and decadent. Ripe cherry submerged in exotic, dark accords for sinful pleasure."
  },
  {
    id: 48,
    name: "Chloe Eau de Parfum",
    brand: "Chloe",
    concentration: "Eau de Parfum",
    gender: "Women",
    fragranceFamily: "Floral Powdery",
    topNotes: ["Peony", "Lychee", "Freesia"],
    heartNotes: ["Rose", "Lily of the Valley", "Magnolia"],
    baseNotes: ["Musk", "Cedar", "Amber"],
    volumeMl: 75,
    priceUSD: 135,
    launchYear: 2008,
    perfumer: "Amandine Clerc-Marie",
    longevity: "Moderate",
    sillage: "Moderate",
    season: ["Spring", "Summer"],
    occasion: ["Daily", "Office"],
    rating: 4.1,
    description: "Effortlessly chic. Fresh roses with a powdery finish, epitomizing Parisian femininity."
  },
  {
    id: 49,
    name: "Boss Bottled",
    brand: "Hugo Boss",
    concentration: "Eau de Toilette",
    gender: "Men",
    fragranceFamily: "Woody Floral",
    topNotes: ["Apple", "Citrus", "Plum", "Bergamot", "Lemon", "Oakmoss", "Geranium"],
    heartNotes: ["Cinnamon", "Mahogany", "Carnation", "Cloves"],
    baseNotes: ["Vanilla", "Sandalwood", "Cedar", "Vetiver", "Olive Tree", "Musk"],
    volumeMl: 100,
    priceUSD: 96,
    launchYear: 1998,
    perfumer: "Annick Menardo",
    longevity: "Moderate",
    sillage: "Moderate",
    season: ["Fall", "Spring"],
    occasion: ["Office", "Daily"],
    rating: 4.0,
    description: "The definition of success. Confident apple and woody notes for the ambitious man."
  },
  {
    id: 50,
    name: "Nomade",
    brand: "Chloe",
    concentration: "Eau de Parfum",
    gender: "Women",
    fragranceFamily: "Chypre Floral",
    topNotes: ["Mirabelle", "Bergamot", "Orange", "Lemon"],
    heartNotes: ["Freesia", "Jasmine", "Rose"],
    baseNotes: ["Oakmoss", "Sandalwood", "Musk", "White Musk"],
    volumeMl: 75,
    priceUSD: 135,
    launchYear: 2018,
    perfumer: "Quentin Bisch",
    longevity: "Long-lasting",
    sillage: "Moderate",
    season: ["Spring", "Summer"],
    occasion: ["Daily", "Office"],
    rating: 4.1,
    description: "Free-spirited wanderlust. A chypre journey with mirabelle plum and wild oakmoss."
  },
  {
    id: 51,
    name: "Gentleman Givenchy",
    brand: "Givenchy",
    concentration: "Eau de Parfum",
    gender: "Men",
    fragranceFamily: "Woody Floral",
    topNotes: ["Pear", "Lavender", "Bergamot", "Cardamom"],
    heartNotes: ["Iris", "Orange Blossom"],
    baseNotes: ["Patchouli", "Leather", "Black Vanilla"],
    volumeMl: 100,
    priceUSD: 120,
    launchYear: 2018,
    perfumer: "Olivier Cresp",
    longevity: "Long-lasting",
    sillage: "Moderate",
    season: ["Fall", "Winter"],
    occasion: ["Evening", "Office"],
    rating: 4.2,
    description: "Modern sophistication. Elegant iris elevated by a dark heart of smoked vanilla."
  },
  {
    id: 52,
    name: "Byredo Gypsy Water",
    brand: "Byredo",
    concentration: "Eau de Parfum",
    gender: "Unisex",
    fragranceFamily: "Woody Aromatic",
    topNotes: ["Bergamot", "Lemon", "Pepper", "Juniper Berries"],
    heartNotes: ["Incense", "Pine Needle", "Orris Root"],
    baseNotes: ["Amber", "Vanilla", "Sandalwood"],
    volumeMl: 100,
    priceUSD: 270,
    launchYear: 2008,
    perfumer: "Olivia Giacobetti",
    longevity: "Moderate",
    sillage: "Moderate",
    season: ["Fall", "Winter"],
    occasion: ["Daily", "Special"],
    rating: 4.2,
    description: "Bohemian romance. A wanderer's soul captured in woodsmoke and pine forests."
  },
  {
    id: 53,
    name: "Versace Pour Homme",
    brand: "Versace",
    concentration: "Eau de Toilette",
    gender: "Men",
    fragranceFamily: "Aromatic Fougere",
    topNotes: ["Lemon", "Bergamot", "Neroli", "Citron"],
    heartNotes: ["Hyacinth", "Clary Sage", "Cedar", "Blue Hyacinth"],
    baseNotes: ["Amber", "Musk", "Saffron"],
    volumeMl: 100,
    priceUSD: 95,
    launchYear: 2008,
    perfumer: "Alberto Morillas",
    longevity: "Moderate",
    sillage: "Moderate",
    season: ["Spring", "Summer"],
    occasion: ["Daily", "Office", "Casual"],
    rating: 4.1,
    description: "Mediterranean refinement. Fresh, elegant, and effortlessly masculine for everyday luxury."
  },
  {
    id: 54,
    name: "Chance Eau Tendre",
    brand: "Chanel",
    concentration: "Eau de Toilette",
    gender: "Women",
    fragranceFamily: "Floral Fruity",
    topNotes: ["Grapefruit", "Quince"],
    heartNotes: ["Hyacinth", "Jasmine"],
    baseNotes: ["White Musk", "Iris", "Virginia Cedar", "Amber"],
    volumeMl: 100,
    priceUSD: 145,
    launchYear: 2010,
    perfumer: "Jacques Polge",
    longevity: "Moderate",
    sillage: "Moderate",
    season: ["Spring", "Summer"],
    occasion: ["Daily", "Office"],
    rating: 4.1,
    description: "Tender and soft. A fruity-floral whisper like a fond embrace."
  },
  {
    id: 55,
    name: "Royal Oud",
    brand: "Creed",
    concentration: "Eau de Parfum",
    gender: "Unisex",
    fragranceFamily: "Woody Spicy",
    topNotes: ["Lemon", "Pink Pepper", "Bergamot"],
    heartNotes: ["Galbanum", "Oud", "Cedar", "Angélica"],
    baseNotes: ["Sandalwood", "Musk"],
    volumeMl: 100,
    priceUSD: 445,
    launchYear: 2011,
    perfumer: "Olivier Creed",
    longevity: "Very long-lasting",
    sillage: "Strong",
    season: ["Fall", "Winter"],
    occasion: ["Evening", "Special"],
    rating: 4.3,
    description: "Regal opulence. Majestic oud wrapped in pink pepper and cedar for royalty."
  },
  {
    id: 56,
    name: "Euphoria",
    brand: "Calvin Klein",
    concentration: "Eau de Parfum",
    gender: "Women",
    fragranceFamily: "Oriental Floral",
    topNotes: ["Pomegranate", "Persimmon", "Green Notes"],
    heartNotes: ["Black Orchid", "Lotus", "Champaca"],
    baseNotes: ["Amber", "Mahogany", "Violet", "Musk", "Black Violet", "Cream"],
    volumeMl: 100,
    priceUSD: 98,
    launchYear: 2005,
    perfumer: "Dominique Ropion",
    longevity: "Long-lasting",
    sillage: "Strong",
    season: ["Fall", "Winter"],
    occasion: ["Evening", "Special"],
    rating: 4.0,
    description: "Intoxicating sensuality. Exotic orchid and pomegranate in a seductive oriental embrace."
  },
  {
    id: 57,
    name: "Burberry Her",
    brand: "Burberry",
    concentration: "Eau de Parfum",
    gender: "Women",
    fragranceFamily: "Floral Fruity Gourmand",
    topNotes: ["Blackberry", "Black Currant", "Raspberry", "Strawberry", "Lemon", "Mandarin Orange", "Sour Cherry"],
    heartNotes: ["Jasmine", "Violet"],
    baseNotes: ["Musk", "Amber", "Sandalwood", "Dry Cocoa", "Benzoin", "Vanilla"],
    volumeMl: 100,
    priceUSD: 135,
    launchYear: 2018,
    perfumer: "Francis Kurkdjian",
    longevity: "Long-lasting",
    sillage: "Moderate",
    season: ["Fall", "Winter"],
    occasion: ["Daily", "Evening"],
    rating: 4.2,
    description: "London spirit. British berries with a heart of jasmine, vibrant and sophisticated."
  },
  {
    id: 58,
    name: "Armaf Club de Nuit Intense",
    brand: "Armaf",
    concentration: "Eau de Toilette",
    gender: "Men",
    fragranceFamily: "Fruity Chypre",
    topNotes: ["Lemon", "Pineapple", "Bergamot", "Black Currant", "Apple"],
    heartNotes: ["Birch", "Jasmine", "Rose"],
    baseNotes: ["Musk", "Ambergris", "Patchouli", "Vanilla"],
    volumeMl: 105,
    priceUSD: 35,
    launchYear: 2015,
    perfumer: "Unknown",
    longevity: "Long-lasting",
    sillage: "Strong",
    season: ["All"],
    occasion: ["Daily", "Office", "Evening"],
    rating: 4.0,
    description: "A crowd-pleasing powerhouse. Fresh pineapple and woods with impressive projection."
  },
  {
    id: 59,
    name: "Iris Silver Mist",
    brand: "Serge Lutens",
    concentration: "Eau de Parfum",
    gender: "Unisex",
    fragranceFamily: "Floral Woody",
    topNotes: ["Galbanum", "Orris Root"],
    heartNotes: ["Iris", "Violet"],
    baseNotes: ["Vetiver", "Woody Notes", "Incense"],
    volumeMl: 50,
    priceUSD: 190,
    launchYear: 1994,
    perfumer: "Christopher Sheldrake",
    longevity: "Very long-lasting",
    sillage: "Moderate",
    season: ["Spring", "Fall"],
    occasion: ["Office", "Special"],
    rating: 4.3,
    description: "Pure iris poetry. Cold, ethereal, and exquisitely refined. A niche masterpiece."
  },
  {
    id: 60,
    name: "Silver Mountain Water",
    brand: "Creed",
    concentration: "Eau de Parfum",
    gender: "Unisex",
    fragranceFamily: "Citrus Aromatic",
    topNotes: ["Bergamot", "Mandarin Orange", "Neroli"],
    heartNotes: ["Green Tea", "Black Currant"],
    baseNotes: ["Musk", "Sandalwood", "Galbanum", "Petit Grain"],
    volumeMl: 100,
    priceUSD: 445,
    launchYear: 1995,
    perfumer: "Olivier Creed",
    longevity: "Moderate",
    sillage: "Moderate",
    season: ["Spring", "Summer"],
    occasion: ["Daily", "Office", "Casual"],
    rating: 4.2,
    description: "Alpine freshness. Crisp green tea and citrus evoking mountain springs and fresh snow."
  },
  {
    id: 61,
    name: "Pure Poison",
    brand: "Dior",
    concentration: "Eau de Parfum",
    gender: "Women",
    fragranceFamily: "Floral White",
    topNotes: ["Orange", "Bergamot", "Mandarin Orange"],
    heartNotes: ["Jasmine", "Orange Blossom", "Gardenia", "White Amber"],
    baseNotes: ["Sandalwood", "Cedar", "Musk", "Amber"],
    volumeMl: 100,
    priceUSD: 130,
    launchYear: 2004,
    perfumer: "Olivier Polge",
    longevity: "Long-lasting",
    sillage: "Moderate",
    season: ["Spring", "Summer"],
    occasion: ["Evening", "Special"],
    rating: 4.1,
    description: "Luminous and hypnotic. Pristine white flowers in a modern, seductive composition."
  },
  {
    id: 62,
    name: "L'Eau d'Issey",
    brand: "Issey Miyake",
    concentration: "Eau de Toilette",
    gender: "Women",
    fragranceFamily: "Floral Aquatic",
    topNotes: ["Lotus", "Freesia", "Cyclamen", "Rose Water", "Melon", "Calone"],
    heartNotes: ["Lily", "Peony", "Lily of the Valley", "Carnation"],
    baseNotes: ["Tuberose", "Sandalwood", "Amber", "Musk", "Cedar", "Osmanthus"],
    volumeMl: 100,
    priceUSD: 110,
    launchYear: 1992,
    perfumer: "Jacques Cavallier",
    longevity: "Moderate",
    sillage: "Moderate",
    season: ["Spring", "Summer"],
    occasion: ["Daily", "Office"],
    rating: 4.0,
    description: "Pure like water. A minimalist aquatic-floral that revolutionized feminine perfumery."
  },
  {
    id: 63,
    name: "Mont Blanc Explorer",
    brand: "Montblanc",
    concentration: "Eau de Parfum",
    gender: "Men",
    fragranceFamily: "Woody Aromatic",
    topNotes: ["Bergamot", "Pink Pepper", "Clary Sage"],
    heartNotes: ["Leather", "Indonesian Vetiver"],
    baseNotes: ["Patchouli", "Cacao Absolute", "Ambroxan", "Akigalawood"],
    volumeMl: 100,
    priceUSD: 88,
    launchYear: 2019,
    perfumer: "Jordi Fernandez",
    longevity: "Long-lasting",
    sillage: "Strong",
    season: ["All"],
    occasion: ["Daily", "Office", "Evening"],
    rating: 4.1,
    description: "Spirit of adventure. Bergamot and vetiver for the modern explorer. An accessible niche style."
  },
  {
    id: 64,
    name: "Prada Candy",
    brand: "Prada",
    concentration: "Eau de Parfum",
    gender: "Women",
    fragranceFamily: "Oriental Vanilla",
    topNotes: ["Caramel"],
    heartNotes: ["Musk", "Benzoin"],
    baseNotes: ["Vanilla", "Benzoin"],
    volumeMl: 80,
    priceUSD: 130,
    launchYear: 2011,
    perfumer: "Daniela Andrier",
    longevity: "Very long-lasting",
    sillage: "Strong",
    season: ["Fall", "Winter"],
    occasion: ["Evening", "Special"],
    rating: 4.1,
    description: "Irresistible sweetness. A bold caramel and musk creation that's impossible to ignore."
  },
  {
    id: 65,
    name: "Ombre Leather",
    brand: "Tom Ford",
    concentration: "Eau de Parfum",
    gender: "Unisex",
    fragranceFamily: "Leather",
    topNotes: ["Cardamom", "Violet Leaf"],
    heartNotes: ["Jasmine Sambac", "Leather"],
    baseNotes: ["Patchouli", "Vetiver", "Amber", "Moss"],
    volumeMl: 100,
    priceUSD: 175,
    launchYear: 2018,
    perfumer: "Sonia Constant",
    longevity: "Very long-lasting",
    sillage: "Strong",
    season: ["Fall", "Winter"],
    occasion: ["Evening", "Special"],
    rating: 4.3,
    description: "American frontier. Supple leather warmed by jasmine and amber. Bold western glamour."
  },
  {
    id: 66,
    name: "L'Imperatrice",
    brand: "Dolce & Gabbana",
    concentration: "Eau de Toilette",
    gender: "Women",
    fragranceFamily: "Floral Fruity",
    topNotes: ["Pink Pepper", "Rhubarb", "Kiwi"],
    heartNotes: ["Watermelon", "Cyclamen", "Jasmine"],
    baseNotes: ["Musk", "Lemon Wood", "Sandalwood"],
    volumeMl: 100,
    priceUSD: 85,
    launchYear: 2009,
    perfumer: "Olivier Cresp",
    longevity: "Moderate",
    sillage: "Moderate",
    season: ["Spring", "Summer"],
    occasion: ["Daily", "Casual"],
    rating: 4.1,
    description: "Seductive empress. Juicy watermelon and kiwi for a playful, flirtatious spirit."
  },
  {
    id: 67,
    name: "Ck One",
    brand: "Calvin Klein",
    concentration: "Eau de Toilette",
    gender: "Unisex",
    fragranceFamily: "Citrus Aromatic",
    topNotes: ["Pineapple", "Green Notes", "Mandarin Orange", "Papaya", "Bergamot", "Cardamom", "Lemon"],
    heartNotes: ["Nutmeg", "Violet", "Orris Root", "Jasmine", "Lily of the Valley", "Rose", "Freesia"],
    baseNotes: ["Amber", "Sandalwood", "Cedar", "Musk", "Oakmoss", "Green Tea Accord"],
    volumeMl: 100,
    priceUSD: 55,
    launchYear: 1994,
    perfumer: "Alberto Morillas",
    longevity: "Moderate",
    sillage: "Moderate",
    season: ["Spring", "Summer"],
    occasion: ["Daily", "Casual"],
    rating: 3.9,
    description: "The original unisex. A generation-defining citrus-musk that democratized fragrance."
  },
  {
    id: 68,
    name: "Jazz Club",
    brand: "Maison Margiela",
    concentration: "Eau de Toilette",
    gender: "Men",
    fragranceFamily: "Woody Aromatic",
    topNotes: ["Pink Pepper", "Lemon", "Neroli"],
    heartNotes: ["Rum Absolute", "Clary Sage", "Java Vetiver"],
    baseNotes: ["Tobacco Leaf", "Vanilla", "Styrax", "Musk"],
    volumeMl: 100,
    priceUSD: 135,
    launchYear: 2013,
    perfumer: "Marie Salamagne",
    longevity: "Long-lasting",
    sillage: "Moderate",
    season: ["Fall", "Winter"],
    occasion: ["Evening", "Special"],
    rating: 4.2,
    description: "Smoky nightlife. Rum, tobacco, and leather evoking a Brooklyn jazz club after hours."
  },
  {
    id: 69,
    name: "Hypnotic Poison",
    brand: "Dior",
    concentration: "Eau de Toilette",
    gender: "Women",
    fragranceFamily: "Oriental Vanilla",
    topNotes: ["Apricot", "Plum", "Coconut"],
    heartNotes: ["Tuberose", "Jasmine", "Lily of the Valley", "Rose", "Caraway"],
    baseNotes: ["Sandalwood", "Almond", "Vanilla", "Musk", "Moss", "Jacaranda Wood"],
    volumeMl: 100,
    priceUSD: 130,
    launchYear: 1998,
    perfumer: "Annick Menardo",
    longevity: "Long-lasting",
    sillage: "Strong",
    season: ["Fall", "Winter"],
    occasion: ["Evening", "Special"],
    rating: 4.1,
    description: "Addictive enchantment. Almond and vanilla in a mysterious, spellbinding embrace."
  },
  {
    id: 70,
    name: "Pegasus",
    brand: "Parfums de Marly",
    concentration: "Eau de Parfum",
    gender: "Men",
    fragranceFamily: "Woody Aromatic",
    topNotes: ["Heliotrope", "Bergamot"],
    heartNotes: ["Bitter Almond", "Jasmine", "Lavender"],
    baseNotes: ["Sandalwood", "Amber", "Vanilla"],
    volumeMl: 125,
    priceUSD: 315,
    launchYear: 2011,
    perfumer: "Hamid Merati-Kashani",
    longevity: "Very long-lasting",
    sillage: "Strong",
    season: ["Fall", "Winter"],
    occasion: ["Evening", "Special"],
    rating: 4.4,
    description: "Mythical elegance. Almond and vanilla in a sophisticated, cloud-like embrace."
  },
  {
    id: 71,
    name: "D&G The One for Women",
    brand: "Dolce & Gabbana",
    concentration: "Eau de Parfum",
    gender: "Women",
    fragranceFamily: "Oriental Floral",
    topNotes: ["Bergamot", "Mandarin Orange", "Lychee", "Peach"],
    heartNotes: ["Madonna Lily", "Jasmine", "Plum", "Muguet"],
    baseNotes: ["Amber", "Musk", "Vanilla", "Vetiver", "Cedar"],
    volumeMl: 75,
    priceUSD: 118,
    launchYear: 2006,
    perfumer: "Olivier Polge",
    longevity: "Long-lasting",
    sillage: "Moderate",
    season: ["Fall", "Winter"],
    occasion: ["Evening", "Special"],
    rating: 4.1,
    description: "Modern classic. Sophisticated florals with warm amber for timeless allure."
  },
  {
    id: 72,
    name: "Eros Flame",
    brand: "Versace",
    concentration: "Eau de Parfum",
    gender: "Men",
    fragranceFamily: "Woody Spicy",
    topNotes: ["Lemon", "Black Pepper", "Chinotto", "Mandarin Orange", "Orange", "Rosemary"],
    heartNotes: ["Geranium", "Pepper", "Rose"],
    baseNotes: ["Sandalwood", "Texas Cedar", "Tonka Bean", "Vanilla", "Patchouli", "Oak Moss"],
    volumeMl: 100,
    priceUSD: 118,
    launchYear: 2018,
    perfumer: "Olivier Pescheux",
    longevity: "Long-lasting",
    sillage: "Strong",
    season: ["Fall", "Winter"],
    occasion: ["Evening", "Special"],
    rating: 4.0,
    description: "Passion ignited. A fiery oriental woody with citrus intensity and amber depth."
  },
  {
    id: 73,
    name: "Noir de Noir",
    brand: "Tom Ford",
    concentration: "Eau de Parfum",
    gender: "Unisex",
    fragranceFamily: "Oriental Floral",
    topNotes: ["Saffron", "Rose"],
    heartNotes: ["Black Rose", "Oud", "Black Truffle"],
    baseNotes: ["Patchouli", "Vanilla", "Tree Moss", "Agarwood"],
    volumeMl: 100,
    priceUSD: 290,
    launchYear: 2007,
    perfumer: "Givaudan",
    longevity: "Very long-lasting",
    sillage: "Strong",
    season: ["Fall", "Winter"],
    occasion: ["Evening", "Special"],
    rating: 4.3,
    description: "Dark romanticism. Mysterious black rose and truffle, earthy and intoxicating."
  },
  {
    id: 74,
    name: "Organza",
    brand: "Givenchy",
    concentration: "Eau de Parfum",
    gender: "Women",
    fragranceFamily: "Floral Woody",
    topNotes: ["Orange Blossom", "Honeysuckle", "Lychee", "Plum", "Green Notes"],
    heartNotes: ["Gardenia", "Jasmine", "Peony", "Ylang-Ylang", "Iris"],
    baseNotes: ["Vanilla", "Guaiac Wood", "Cedar", "Amber", "Musk"],
    volumeMl: 100,
    priceUSD: 120,
    launchYear: 1996,
    perfumer: "Sophie Labbe",
    longevity: "Long-lasting",
    sillage: "Moderate",
    season: ["Spring", "Fall"],
    occasion: ["Evening", "Special"],
    rating: 4.0,
    description: "Refined elegance. A rich white floral with honeysuckle and gardenia in silk-like accord."
  },
  {
    id: 75,
    name: "Polo Blue",
    brand: "Ralph Lauren",
    concentration: "Eau de Toilette",
    gender: "Men",
    fragranceFamily: "Woody Aquatic",
    topNotes: ["Melon", "Cucumber", "Mandarin Orange"],
    heartNotes: ["Basil", "Clary Sage", "Verbena", "Geranium"],
    baseNotes: ["Suede", "Woodsy Notes", "Musk", "Patchouli"],
    volumeMl: 125,
    priceUSD: 102,
    launchYear: 2002,
    perfumer: "Carlos Benaim",
    longevity: "Moderate",
    sillage: "Moderate",
    season: ["Spring", "Summer"],
    occasion: ["Daily", "Casual", "Office"],
    rating: 4.0,
    description: "Freedom and adventure. Fresh aquatic cucumber and melon for laid-back confidence."
  },
  {
    id: 76,
    name: "La Nuit de L'Homme",
    brand: "Yves Saint Laurent",
    concentration: "Eau de Toilette",
    gender: "Men",
    fragranceFamily: "Oriental Fougere",
    topNotes: ["Cardamom", "Star Anise", "Bergamot", "Lavender"],
    heartNotes: ["Lavender", "Cumin", "Violet"],
    baseNotes: ["Vetiver", "Caraway", "Cedar", "Coumarin"],
    volumeMl: 100,
    priceUSD: 115,
    launchYear: 2009,
    perfumer: "Anne Flipo",
    longevity: "Moderate",
    sillage: "Moderate",
    season: ["Fall", "Winter"],
    occasion: ["Evening", "Special"],
    rating: 4.3,
    description: "Seduction after dark. Sensual cardamom and lavender for nocturnal magnetism."
  },
  {
    id: 77,
    name: "Bright Crystal",
    brand: "Versace",
    concentration: "Eau de Toilette",
    gender: "Women",
    fragranceFamily: "Floral Fruity",
    topNotes: ["Pomegranate", "Yuzu", "Frost Accord"],
    heartNotes: ["Peony", "Magnolia", "Lotus"],
    baseNotes: ["Amber", "Musk", "Mahogany", "Vegetal Amber"],
    volumeMl: 90,
    priceUSD: 118,
    launchYear: 2006,
    perfumer: "Alberto Morillas",
    longevity: "Moderate",
    sillage: "Moderate",
    season: ["Spring", "Summer"],
    occasion: ["Daily", "Casual"],
    rating: 4.0,
    description: "Crystal clarity. Fresh pomegranate and magnolia like morning light through dewdrops."
  },
  {
    id: 78,
    name: "Santal 33",
    brand: "Le Labo",
    concentration: "Eau de Parfum",
    gender: "Unisex",
    fragranceFamily: "Woody Aromatic",
    topNotes: ["Cardamom", "Iris", "Violet"],
    heartNotes: ["Ambrox", "Australian Sandalwood", "Papyrus"],
    baseNotes: ["Cedarwood", "Leather", "Musk"],
    volumeMl: 100,
    priceUSD: 317,
    launchYear: 2011,
    perfumer: "Frank Voelkl",
    longevity: "Very long-lasting",
    sillage: "Strong",
    season: ["Fall", "Winter"],
    occasion: ["Daily", "Office", "Special"],
    rating: 4.3,
    description: "Urban cult classic. Distinctive sandalwood and leather with addictive violet accord."
  },
  {
    id: 79,
    name: "Luna Rossa Carbon",
    brand: "Prada",
    concentration: "Eau de Toilette",
    gender: "Men",
    fragranceFamily: "Aromatic Fougere",
    topNotes: ["Bergamot", "Pepper"],
    heartNotes: ["Lavender"],
    baseNotes: ["Patchouli", "Ambroxan"],
    volumeMl: 100,
    priceUSD: 110,
    launchYear: 2017,
    perfumer: "Daniela Andrier",
    longevity: "Long-lasting",
    sillage: "Strong",
    season: ["All"],
    occasion: ["Daily", "Office", "Evening"],
    rating: 4.0,
    description: "High-tech freshness. A modern aromatic fougere with synthetic precision."
  },
  {
    id: 80,
    name: "Tiffany & Co Eau de Parfum",
    brand: "Tiffany & Co",
    concentration: "Eau de Parfum",
    gender: "Women",
    fragranceFamily: "Floral Musky",
    topNotes: ["Mandarin Orange", "Vert de Mandarine", "Lemon"],
    heartNotes: ["Iris", "Noble Iris"],
    baseNotes: ["Patchouli", "Musk", "Cashmeran"],
    volumeMl: 75,
    priceUSD: 135,
    launchYear: 2017,
    perfumer: "Daniela Andrier",
    longevity: "Long-lasting",
    sillage: "Moderate",
    season: ["Spring", "Summer"],
    occasion: ["Office", "Daily", "Special"],
    rating: 4.0,
    description: "New York elegance. Sophisticated iris and musk capturing the spirit of Tiffany's iconic blue."
  },
  {
    id: 81,
    name: "Oud Ispahan",
    brand: "Dior",
    concentration: "Eau de Parfum",
    gender: "Unisex",
    fragranceFamily: "Oriental Woody",
    topNotes: ["Damask Rose"],
    heartNotes: ["Oud", "Labdanum"],
    baseNotes: ["Sandalwood", "Benzoin", "Incense"],
    volumeMl: 125,
    priceUSD: 320,
    launchYear: 2012,
    perfumer: "François Demachy",
    longevity: "Very long-lasting",
    sillage: "Strong",
    season: ["Fall", "Winter"],
    occasion: ["Evening", "Special"],
    rating: 4.4,
    description: "Eastern romance. Magnificent rose intertwined with precious oud from the Middle East."
  },
  {
    id: 82,
    name: "Scandal",
    brand: "Jean Paul Gaultier",
    concentration: "Eau de Parfum",
    gender: "Women",
    fragranceFamily: "Oriental Chypre",
    topNotes: ["Blood Orange", "Mandarin Orange"],
    heartNotes: ["Honey", "Gardenia"],
    baseNotes: ["Patchouli", "Caramel", "Beeswax", "Licorice"],
    volumeMl: 80,
    priceUSD: 118,
    launchYear: 2017,
    perfumer: "Daphne Bugey",
    longevity: "Very long-lasting",
    sillage: "Strong",
    season: ["Fall", "Winter"],
    occasion: ["Evening", "Special"],
    rating: 4.1,
    description: "Provocative allure. A honey-drenched scandal that's sweet, daring, and unforgettable."
  },
  {
    id: 83,
    name: "Acqua di Gio Profumo",
    brand: "Giorgio Armani",
    concentration: "Eau de Parfum",
    gender: "Men",
    fragranceFamily: "Aquatic Aromatic",
    topNotes: ["Bergamot", "Sea Notes", "Aquatic Notes", "Geranium"],
    heartNotes: ["Rosemary", "Sage", "Cypress"],
    baseNotes: ["Patchouli", "Incense", "Amber"],
    volumeMl: 125,
    priceUSD: 148,
    launchYear: 2015,
    perfumer: "Alberto Morillas",
    longevity: "Long-lasting",
    sillage: "Moderate",
    season: ["Spring", "Summer", "Fall"],
    occasion: ["Office", "Evening", "Daily"],
    rating: 4.4,
    description: "Elevated elegance. The essence of the Mediterranean intensified with aromatic incense."
  },
  {
    id: 84,
    name: "Princess",
    brand: "Vera Wang",
    concentration: "Eau de Toilette",
    gender: "Women",
    fragranceFamily: "Floral Fruity",
    topNotes: ["Apple", "Water Lily", "Apricot", "Mandarin Orange"],
    heartNotes: ["Guava", "Tiare Flower", "Tuberose", "Dark Chocolate"],
    baseNotes: ["Amber", "Vanilla", "Woods", "Musk"],
    volumeMl: 100,
    priceUSD: 70,
    launchYear: 2006,
    perfumer: "Rodrigo Flores-Roux",
    longevity: "Moderate",
    sillage: "Moderate",
    season: ["Spring", "Summer"],
    occasion: ["Daily", "Casual"],
    rating: 3.9,
    description: "Youthful whimsy. A playful fruity floral with unexpected chocolate for the spirited."
  },
  {
    id: 85,
    name: "Noir Extreme",
    brand: "Tom Ford",
    concentration: "Eau de Parfum",
    gender: "Men",
    fragranceFamily: "Oriental Spicy",
    topNotes: ["Cardamom", "Neroli", "Mandarin Orange", "Nutmeg", "Saffron"],
    heartNotes: ["Kulfi", "Rose Absolute", "Jasmine", "Orange Blossom"],
    baseNotes: ["Sandalwood", "Amber", "Vanilla", "Woody Notes"],
    volumeMl: 100,
    priceUSD: 175,
    launchYear: 2015,
    perfumer: "Olivier Gillotin",
    longevity: "Very long-lasting",
    sillage: "Strong",
    season: ["Fall", "Winter"],
    occasion: ["Evening", "Special"],
    rating: 4.3,
    description: "Opulent intensity. Kulfi-inspired gourmand warmth with exotic oriental sophistication."
  },
  {
    id: 86,
    name: "Wood Sage & Sea Salt",
    brand: "Jo Malone",
    concentration: "Cologne",
    gender: "Unisex",
    fragranceFamily: "Woody Aromatic",
    topNotes: ["Ambrette Seeds"],
    heartNotes: ["Sea Salt"],
    baseNotes: ["Sage", "Driftwood"],
    volumeMl: 100,
    priceUSD: 155,
    launchYear: 2014,
    perfumer: "Christine Nagel",
    longevity: "Moderate",
    sillage: "Intimate",
    season: ["Spring", "Summer"],
    occasion: ["Daily", "Casual"],
    rating: 4.1,
    description: "Windswept coast. Sea salt and sage evoking craggy cliffs and ocean breeze."
  },
  {
    id: 87,
    name: "Ultra Male",
    brand: "Jean Paul Gaultier",
    concentration: "Eau de Toilette Intense",
    gender: "Men",
    fragranceFamily: "Oriental Fougere",
    topNotes: ["Pear", "Bergamot", "Mint", "Lavender", "Black Pepper"],
    heartNotes: ["Cinnamon", "Sage"],
    baseNotes: ["Vanilla", "Black Vanilla", "Amber", "Cedar"],
    volumeMl: 125,
    priceUSD: 106,
    launchYear: 2015,
    perfumer: "Francis Kurkdjian",
    longevity: "Very long-lasting",
    sillage: "Strong",
    season: ["Fall", "Winter"],
    occasion: ["Evening", "Special"],
    rating: 4.1,
    description: "Hyper-seduction. A sweeter, more intense take on the iconic Le Male."
  },
  {
    id: 88,
    name: "Rose Goldea",
    brand: "Bvlgari",
    concentration: "Eau de Parfum",
    gender: "Women",
    fragranceFamily: "Oriental Floral",
    topNotes: ["Pomegranate"],
    heartNotes: ["Damask Rose", "Jasmine", "Rose Absolute", "Rose de Mai"],
    baseNotes: ["Musk", "Sandalwood", "Oud"],
    volumeMl: 90,
    priceUSD: 130,
    launchYear: 2016,
    perfumer: "Alberto Morillas",
    longevity: "Long-lasting",
    sillage: "Moderate",
    season: ["Fall", "Winter"],
    occasion: ["Evening", "Special"],
    rating: 4.0,
    description: "Golden goddess. Luxurious rose and musk inspired by ancient queens and their jewels."
  },
  {
    id: 89,
    name: "Chanel Allure Homme Sport",
    brand: "Chanel",
    concentration: "Eau de Toilette",
    gender: "Men",
    fragranceFamily: "Woody Fresh Spicy",
    topNotes: ["Orange", "Sea Notes", "Aldehydes"],
    heartNotes: ["Neroli", "Cedar", "Pepper"],
    baseNotes: ["Musk", "Tonka Bean", "Vanilla", "Amber"],
    volumeMl: 100,
    priceUSD: 140,
    launchYear: 2004,
    perfumer: "Jacques Polge",
    longevity: "Moderate",
    sillage: "Moderate",
    season: ["Spring", "Summer"],
    occasion: ["Sport", "Casual", "Daily"],
    rating: 4.1,
    description: "Dynamic energy. Fresh neroli and pepper for the active modern man."
  },
  {
    id: 90,
    name: "Red Door",
    brand: "Elizabeth Arden",
    concentration: "Eau de Toilette",
    gender: "Women",
    fragranceFamily: "Floral",
    topNotes: ["Moroccan Orange Blossom", "Rose", "Freesia", "Lily of the Valley", "Ylang-Ylang"],
    heartNotes: ["Orchid", "Jasmine", "Rose", "Wild Violet"],
    baseNotes: ["Sandalwood", "Honey", "Oakmoss", "Benzoin", "Vetiver", "Musk"],
    volumeMl: 100,
    priceUSD: 65,
    launchYear: 1989,
    perfumer: "Carlos Benaim",
    longevity: "Long-lasting",
    sillage: "Strong",
    season: ["Spring", "Fall"],
    occasion: ["Evening", "Special"],
    rating: 3.8,
    description: "Glamorous classic. An opulent bouquet of roses and orchids for sophisticated evenings."
  },
  {
    id: 91,
    name: "Colonia",
    brand: "Acqua di Parma",
    concentration: "Eau de Cologne",
    gender: "Unisex",
    fragranceFamily: "Citrus Aromatic",
    topNotes: ["Lavender", "Sicilian Citrus", "Orange", "Bergamot", "Lemon"],
    heartNotes: ["Bulgarian Rose", "Verbena", "Rosemary"],
    baseNotes: ["Sandalwood", "Patchouli", "Vetiver", "Musk"],
    volumeMl: 180,
    priceUSD: 250,
    launchYear: 1916,
    perfumer: "Unknown",
    longevity: "Moderate",
    sillage: "Moderate",
    season: ["Spring", "Summer"],
    occasion: ["Daily", "Office"],
    rating: 4.2,
    description: "Italian heritage. A century of elegance in sparkling citrus and lavender."
  },
  {
    id: 92,
    name: "Rive Gauche",
    brand: "Yves Saint Laurent",
    concentration: "Eau de Toilette",
    gender: "Women",
    fragranceFamily: "Floral Aldehyde",
    topNotes: ["Aldehydes", "Bergamot", "Ylang-Ylang", "Peach", "Gardenia"],
    heartNotes: ["Rose", "Jasmine", "Geranium", "Orris Root", "Lily of the Valley", "Magnolia"],
    baseNotes: ["Vetiver", "Sandalwood", "Oakmoss", "Musk", "Tonka Bean", "Benzoin"],
    volumeMl: 100,
    priceUSD: 85,
    launchYear: 1971,
    perfumer: "Jacques Polge",
    longevity: "Long-lasting",
    sillage: "Moderate",
    season: ["Spring", "Fall"],
    occasion: ["Office", "Daily"],
    rating: 4.0,
    description: "Parisian chic. Revolutionary aldehydic florals that captured the spirit of modern feminism."
  },
  {
    id: 93,
    name: "Amber Pour Homme",
    brand: "Prada",
    concentration: "Eau de Toilette",
    gender: "Men",
    fragranceFamily: "Oriental Fougere",
    topNotes: ["Cardamom", "Bergamot", "Mandarin Orange", "Neroli"],
    heartNotes: ["Orange Blossom", "Myrrh", "Vetiver", "Geranium"],
    baseNotes: ["Labdanum", "Amber", "Vanilla", "Saffron", "Sandalwood", "Tonka Bean", "Leather", "Patchouli"],
    volumeMl: 100,
    priceUSD: 115,
    launchYear: 2006,
    perfumer: "Daniela Andrier",
    longevity: "Long-lasting",
    sillage: "Moderate",
    season: ["Fall", "Winter"],
    occasion: ["Office", "Evening"],
    rating: 4.2,
    description: "Refined luxury. Saffron and amber in a sophisticated Italian fashion statement."
  },
  {
    id: 94,
    name: "24 Faubourg",
    brand: "Hermès",
    concentration: "Eau de Toilette",
    gender: "Women",
    fragranceFamily: "Floral Fruity",
    topNotes: ["Orange Blossom", "Peach", "White Flowers"],
    heartNotes: ["Tiare Flower", "Jasmine", "Ylang-Ylang", "Iris", "Orange Blossom"],
    baseNotes: ["Ambergris", "Sandalwood", "Patchouli", "Vanilla", "Benzoin"],
    volumeMl: 100,
    priceUSD: 165,
    launchYear: 1995,
    perfumer: "Maurice Roucel",
    longevity: "Long-lasting",
    sillage: "Moderate",
    season: ["Spring", "Summer"],
    occasion: ["Office", "Daily", "Special"],
    rating: 4.1,
    description: "Haute couture address. Sun-drenched white florals named after Hermès' Paris boutique."
  },
  {
    id: 95,
    name: "Very Irresistible",
    brand: "Givenchy",
    concentration: "Eau de Toilette",
    gender: "Women",
    fragranceFamily: "Floral Fruity",
    topNotes: ["Star Anise", "Lemon", "Rose Centifolia"],
    heartNotes: ["Peony", "Rose", "Fantasy Verbena", "Peach"],
    baseNotes: ["Amber", "Patchouli", "Musk", "Virginian Cedar", "Vanilla"],
    volumeMl: 75,
    priceUSD: 95,
    launchYear: 2003,
    perfumer: "Dominique Ropion",
    longevity: "Moderate",
    sillage: "Moderate",
    season: ["Spring", "Summer"],
    occasion: ["Daily", "Casual"],
    rating: 4.0,
    description: "Vibrant joy. A sparkling rose cocktail with anise and verbena. Pure happiness."
  },
  {
    id: 96,
    name: "Layton",
    brand: "Parfums de Marly",
    concentration: "Eau de Parfum",
    gender: "Unisex",
    fragranceFamily: "Amber Spicy",
    topNotes: ["Apple", "Bergamot", "Mandarin Orange", "Lavender"],
    heartNotes: ["Jasmine", "Violet", "Geranium"],
    baseNotes: ["Vanilla", "Pepper", "Sandalwood", "Cardamom", "Guaiac Wood", "Patchouli"],
    volumeMl: 125,
    priceUSD: 315,
    launchYear: 2016,
    perfumer: "Hamid Merati-Kashani",
    longevity: "Very long-lasting",
    sillage: "Strong",
    season: ["Fall", "Winter"],
    occasion: ["Evening", "Special"],
    rating: 4.5,
    description: "Noble elegance. Sophisticated apple and vanilla in a luxurious, regal composition."
  },
  {
    id: 97,
    name: "Roses de Chloe",
    brand: "Chloe",
    concentration: "Eau de Toilette",
    gender: "Women",
    fragranceFamily: "Floral",
    topNotes: ["Bergamot"],
    heartNotes: ["Damask Rose", "Rose Essence", "Magnolia"],
    baseNotes: ["Musk", "Amber", "White Musk"],
    volumeMl: 75,
    priceUSD: 115,
    launchYear: 2013,
    perfumer: "Michel Almairac",
    longevity: "Moderate",
    sillage: "Moderate",
    season: ["Spring", "Summer"],
    occasion: ["Daily", "Office"],
    rating: 4.0,
    description: "Rose garden freshness. A bouquet of innocent, dewy roses for everyday elegance."
  },
  {
    id: 98,
    name: "Declaration",
    brand: "Cartier",
    concentration: "Eau de Toilette",
    gender: "Men",
    fragranceFamily: "Woody Spicy",
    topNotes: ["Artemisia", "Coriander", "Cardamom", "Caraway", "Neroli", "Birch"],
    heartNotes: ["Cedar", "Iris", "Juniper", "Pepper", "Leather", "Ginger"],
    baseNotes: ["Vetiver", "Oakmoss", "Amber", "Musk", "Tonka Bean"],
    volumeMl: 100,
    priceUSD: 115,
    launchYear: 1998,
    perfumer: "Jean-Claude Ellena",
    longevity: "Long-lasting",
    sillage: "Moderate",
    season: ["All"],
    occasion: ["Office", "Daily"],
    rating: 4.1,
    description: "Confident statement. Artemisia and cumin in an audacious, unforgettable declaration."
  },
  {
    id: 99,
    name: "Modern Muse",
    brand: "Estée Lauder",
    concentration: "Eau de Parfum",
    gender: "Women",
    fragranceFamily: "Woody Floral",
    topNotes: ["Mandarin Orange", "Tuberose", "Jasmine Sambac"],
    heartNotes: ["Tuberose", "Chinese Sambac Jasmine"],
    baseNotes: ["Amber Wood", "Vanilla", "Patchouli", "Musk"],
    volumeMl: 100,
    priceUSD: 128,
    launchYear: 2013,
    perfumer: "Harry Fremont",
    longevity: "Long-lasting",
    sillage: "Moderate",
    season: ["Spring", "Fall"],
    occasion: ["Office", "Evening"],
    rating: 4.0,
    description: "Creative confidence. Sparkling jasmine and patchouli for the inspiring achiever."
  },
  {
    id: 100,
    name: "Green Irish Tweed",
    brand: "Creed",
    concentration: "Eau de Parfum",
    gender: "Men",
    fragranceFamily: "Woody Aromatic",
    topNotes: ["Lemon Verbena", "Peppermint", "Iris"],
    heartNotes: ["Violet Leaf", "Florentine Iris"],
    baseNotes: ["Mysore Sandalwood", "Ambergris"],
    volumeMl: 100,
    priceUSD: 445,
    launchYear: 1985,
    perfumer: "Olivier Creed",
    longevity: "Long-lasting",
    sillage: "Moderate",
    season: ["Spring", "Summer", "Fall"],
    occasion: ["Office", "Daily", "Special"],
    rating: 4.4,
    description: "Countryside nobility. Irish emerald meadows captured in violet leaf and sandalwood."
  }
]

// Image filename mapping (based on actual files in uploads/products)
const imageFilenames: Record<number, string> = {
  1: '1-chanel-no-5.png',
  2: '2-dior-sauvage.png',
  3: '3-tom-ford-black-orchid.png',
  4: '4-lanc-me-la-vie-est-belle.png',
  5: '5-chanel-bleu-de-chanel.png',
  6: '6-dolce-gabbana-light-blue.png',
  7: '7-creed-aventus.png',
  8: '8-chanel-coco-mademoiselle.png',
  9: '9-giorgio-armani-acqua-di-gio.png',
  10: '10-dior-miss-dior.png',
  11: '11-paco-rabanne-1-million.png',
  12: '12-dior-j-adore.png',
  13: '13-tom-ford-oud-wood.png',
  14: '14-carolina-herrera-good-girl.png',
  15: '15-herm-s-terre-d-herm-s.png',
  16: '16-viktor-rolf-flowerbomb.png',
  17: '17-jean-paul-gaultier-le-male.png',
  18: '18-maison-francis-kurkdjian-baccarat-rouge-540.png',
  19: '19-chanel-chance.png',
  20: '20-dior-dior-homme-intense.png',
  21: '21-dior-poison.png',
  22: '22-versace-versace-eros.png',
  23: '23-narciso-rodriguez-narciso-rodriguez-for-her.png',
  24: '24-yves-saint-laurent-ysl-libre.png',
  25: '25-valentino-valentino-uomo.png',
  26: '26-yves-saint-laurent-mon-paris.png',
  27: '27-dior-fahrenheit.png',
  28: '28-guerlain-shalimar.png',
  29: '29-versace-dylan-blue.png',
  30: '30-mugler-alien.png',
  31: '31-mugler-angel.png',
  32: '32-dolce-gabbana-the-one.png',
  33: '33-yves-saint-laurent-black-opium.png',
  34: '34-paco-rabanne-invictus.png',
  35: '35-giorgio-armani-si.png',
  36: '36-frederic-malle-portrait-of-a-lady.png',
  37: '37-viktor-rolf-spicebomb.png',
  38: '38-givenchy-l-interdit.png',
  39: '39-gucci-gucci-bloom.png',
  40: '40-tom-ford-tobacco-vanille.png',
  41: '41-giorgio-armani-my-way.png',
  42: '42-yves-saint-laurent-l-homme.png',
  43: '43-versace-eros-pour-femme.png',
  44: '44-amouage-interlude-man.png',
  45: '45-parfums-de-marly-delina.png',
  46: '46-davidoff-cool-water.png',
  47: '47-tom-ford-lost-cherry.png',
  48: '48-chloe-chloe-eau-de-parfum.png',
  49: '49-hugo-boss-boss-bottled.png',
  50: '50-chloe-nomade.png',
  51: '51-givenchy-gentleman-givenchy.png',
  52: '52-byredo-byredo-gypsy-water.png',
  53: '53-versace-versace-pour-homme.png',
  54: '54-chanel-chance-eau-tendre.png',
  55: '55-creed-royal-oud.png',
  56: '56-calvin-klein-euphoria.png',
  57: '57-burberry-burberry-her.png',
  58: '58-armaf-armaf-club-de-nuit-intense.png',
  59: '59-serge-lutens-iris-silver-mist.png',
  60: '60-creed-silver-mountain-water.png',
  61: '61-dior-pure-poison.png',
  62: '62-issey-miyake-l-eau-d-issey.png',
  63: '63-montblanc-mont-blanc-explorer.png',
  64: '64-prada-prada-candy.png',
  65: '65-tom-ford-ombre-leather.png',
  66: '66-dolce-gabbana-l-imperatrice.png',
  67: '67-calvin-klein-ck-one.png',
  68: '68-maison-margiela-jazz-club.png',
  69: '69-dior-hypnotic-poison.png',
  70: '70-parfums-de-marly-pegasus.png',
  71: '71-dolce-gabbana-d-g-the-one-for-women.png',
  72: '72-versace-eros-flame.png',
  73: '73-tom-ford-noir-de-noir.png',
  74: '74-givenchy-organza.png',
  75: '75-ralph-lauren-polo-blue.png',
  76: '76-yves-saint-laurent-la-nuit-de-l-homme.png',
  77: '77-versace-bright-crystal.png',
  78: '78-le-labo-santal-33.png',
  79: '79-prada-luna-rossa-carbon.png',
  80: '80-tiffany-co-tiffany-co-eau-de-parfum.png',
  81: '81-dior-oud-ispahan.png',
  82: '82-jean-paul-gaultier-scandal.png',
  83: '83-giorgio-armani-acqua-di-gio-profumo.png',
  84: '84-vera-wang-princess.png',
  85: '85-tom-ford-noir-extreme.png',
  86: '86-jo-malone-wood-sage-sea-salt.png',
  87: '87-jean-paul-gaultier-ultra-male.png',
  88: '88-bvlgari-rose-goldea.png',
  89: '89-chanel-chanel-allure-homme-sport.png',
  90: '90-elizabeth-arden-red-door.png',
  91: '91-acqua-di-parma-colonia.png',
  92: '92-yves-saint-laurent-rive-gauche.png',
  93: '93-prada-amber-pour-homme.png',
  94: '94-herm-s-24-faubourg.png',
  95: '95-givenchy-very-irresistible.png',
  96: '96-parfums-de-marly-layton.png',
  97: '97-chloe-roses-de-chloe.png',
  98: '98-cartier-declaration.png',
  99: '99-est-e-lauder-modern-muse.png',
  100: '100-creed-green-irish-tweed.png'
}

async function main() {
  // Create admin user with password from env or generate secure random
  const adminPasswordPlain = process.env.ADMIN_SEED_PASSWORD || generateSecurePassword()
  const isGenerated = !process.env.ADMIN_SEED_PASSWORD
  const adminPassword = await bcrypt.hash(adminPasswordPlain, 10)

  const admin = await prisma.user.upsert({
    where: { email: 'admin@perfumes.store' },
    update: {},
    create: {
      email: 'admin@perfumes.store',
      passwordHash: adminPassword,
      name: 'Admin',
      role: Role.ADMIN,
    },
  })

  console.log('Created admin user:', admin.email)
  if (isGenerated) {
    console.log('⚠️  Generated admin password:', adminPasswordPlain)
    console.log('   Save this password! It will not be shown again.')
  }

  // Collect all unique fragrance families from perfume data
  const fragranceFamilySet = new Set<string>()
  perfumes.forEach(p => fragranceFamilySet.add(p.fragranceFamily))
  const fragranceFamilies = Array.from(fragranceFamilySet)

  // Collect all unique longevities
  const longevitySet = new Set<string>()
  perfumes.forEach(p => longevitySet.add(p.longevity))
  const longevities = [
    { name: 'Weak', sortOrder: 1 },
    { name: 'Moderate', sortOrder: 2 },
    { name: 'Long-lasting', sortOrder: 3 },
    { name: 'Very long-lasting', sortOrder: 4 },
  ]

  // Collect all unique sillages
  const sillages = [
    { name: 'Intimate', sortOrder: 1 },
    { name: 'Moderate', sortOrder: 2 },
    { name: 'Strong', sortOrder: 3 },
    { name: 'Enormous', sortOrder: 4 },
  ]

  const seasons = ['Spring', 'Summer', 'Fall', 'Winter']

  // Collect unique occasions from perfume data
  const occasionSet = new Set<string>()
  perfumes.forEach(p => p.occasion.forEach(o => occasionSet.add(o)))
  const occasions = Array.from(occasionSet)

  // Upsert fragrance families
  for (const name of fragranceFamilies) {
    await prisma.fragranceFamily.upsert({
      where: { name },
      update: {},
      create: { name },
    })
  }
  console.log('Seeded fragrance families:', fragranceFamilies.length)

  // Upsert longevities
  for (const { name, sortOrder } of longevities) {
    await prisma.longevity.upsert({
      where: { name },
      update: { sortOrder },
      create: { name, sortOrder },
    })
  }
  console.log('Seeded longevities')

  // Upsert sillages
  for (const { name, sortOrder } of sillages) {
    await prisma.sillage.upsert({
      where: { name },
      update: { sortOrder },
      create: { name, sortOrder },
    })
  }
  console.log('Seeded sillages')

  // Upsert seasons
  for (const name of seasons) {
    await prisma.season.upsert({
      where: { name },
      update: {},
      create: { name },
    })
  }
  console.log('Seeded seasons')

  // Upsert occasions
  for (const name of occasions) {
    await prisma.occasion.upsert({
      where: { name },
      update: {},
      create: { name },
    })
  }
  console.log('Seeded occasions:', occasions)

  // Fetch all lookup data
  const allFragranceFamilies = await prisma.fragranceFamily.findMany()
  const allLongevities = await prisma.longevity.findMany()
  const allSillages = await prisma.sillage.findMany()
  const allSeasons = await prisma.season.findMany()
  const allOccasions = await prisma.occasion.findMany()

  // Create maps for quick lookup
  const fragranceFamilyMap = new Map(allFragranceFamilies.map(f => [f.name, f.id]))
  const longevityMap = new Map(allLongevities.map(l => [l.name, l.id]))
  const sillageMap = new Map(allSillages.map(s => [s.name, s.id]))
  const seasonMap = new Map(allSeasons.map(s => [s.name, s.id]))
  const occasionMap = new Map(allOccasions.map(o => [o.name, o.id]))

  // Delete existing products before seeding new ones
  await prisma.product.deleteMany({})
  console.log('Cleared existing products')

  // Create products
  for (const perfume of perfumes) {
    const fragranceFamilyId = fragranceFamilyMap.get(perfume.fragranceFamily)
    const longevityId = longevityMap.get(perfume.longevity)
    const sillageId = sillageMap.get(perfume.sillage)

    if (!fragranceFamilyId || !longevityId || !sillageId) {
      console.error(`Missing lookup data for ${perfume.name}:`, {
        fragranceFamilyId,
        longevityId,
        sillageId,
      })
      continue
    }

    // Handle "All" season by connecting to all seasons
    const seasonIds = perfume.season.includes('All')
      ? allSeasons.map(s => ({ id: s.id }))
      : perfume.season
          .map(s => seasonMap.get(s))
          .filter((id): id is number => id !== undefined)
          .map(id => ({ id }))

    const occasionIds = perfume.occasion
      .map(o => occasionMap.get(o))
      .filter((id): id is number => id !== undefined)
      .map(id => ({ id }))

    // Generate random stock between 50 and 200
    const stock = Math.floor(Math.random() * 151) + 50

    // Get image filename
    const imageFilename = imageFilenames[perfume.id]
    const imageUrl = imageFilename ? `/uploads/products/${imageFilename}` : null

    // Generate SEO-friendly slug
    const slug = generateSlug(perfume.brand, perfume.name, perfume.concentration)

    await prisma.product.create({
      data: {
        slug,
        name: perfume.name,
        brand: perfume.brand,
        concentration: mapConcentration(perfume.concentration),
        gender: mapGender(perfume.gender),
        fragranceFamilyId,
        topNotes: perfume.topNotes,
        heartNotes: perfume.heartNotes,
        baseNotes: perfume.baseNotes,
        volumeMl: perfume.volumeMl,
        priceRON: perfume.priceUSD, // Using USD as RON for now
        launchYear: perfume.launchYear,
        perfumer: perfume.perfumer,
        longevityId,
        sillageId,
        seasons: { connect: seasonIds },
        occasions: { connect: occasionIds },
        rating: perfume.rating,
        stock,
        imageUrl,
        description: perfume.description,
      },
    })
    console.log(`Created product: ${perfume.name}`)
  }

  console.log(`Seeding complete. Created ${perfumes.length} products.`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
